title: Pratik Nilange
description: Random musings on life.
twitty:
  name: Pratik Nilange
  summary: "Musings on tech, design, and life."
  username: PratikNilange
  location: Bengaluru, India
  url: /about
  url-text: pratik.nl/about
  since: 2023
  cover-img: "https://pbs.twimg.com/profile_banners/1276902541360418816/1617333212/1500x500"
  profile-img: "https://pbs.twimg.com/profile_images/1375834857570324482/0XEJ9-7x_400x400.jpg"
sass:
  style: compressed
permalink: pretty