title: Pratik Nilange
tagline: Musings on tech, design, and life.
description: Musings on tech, design, and life.
url: https://pratik.nl
author: pratiknilange
twitter:
  username: pratiknilange
  card: summary
social:
  name: Pratik Nilange
  links:
    - https://twitter.com/pratiknilange
    - https://facebook.com/pratnil
    - https://linkedin.com/in/npt
    - https://github.com/pratiknilange
    - https://www.flickr.com/photos/186635911@N03/
    - https://instagram.com/pratiknilange
    - https://www.goodreads.com/review/list/120733875?shelf=read
locale: en_US

permalink: pretty

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md

footer: '#NSNO' # 'bad puns on <a href="https://twitter.com/pratiknilange">twitter</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
