site: Pratik Nilange
url: https://pratik.nl #yoururl
title: Pratik Nilange
description: Musings on tech, design, and life.
twitter:
  username: pratiknilange #yourusername
  card: summary
  creator: pratiknilange #yourusername
author:
  twitter: pratiknilange #yourusername
  name: pratiknilange #yourusername
  avatar:
  email: #youremail
  url: pratik.nl #yoururl
permalink: pretty

baseurl: ""
destination: docs
highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"