# site
title: Pratik Nilange
baseurl: ""
url: "http://pratik.nl"
favicon: "/assets/sample/ico.png"
g_analytics:

# bio
header: Pratik Nilange
desc: >
  Musings on tech, design, and life.

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock